#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Enable Development Mode Without API Keys

set -e

echo "========================================"
echo "Love Ledger - Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Check for .env.local file
if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}No .env.local file found.${NC}"
    echo -e "${GREEN}Running in Dev Mode - Mock services will be used.${NC}"
    echo ""
fi

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

# Start Next.js in background
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js: http://localhost:3000"
echo ""
echo "Demo Pages:"
echo "  Home:          http://localhost:3000"
echo "  Avatar Builder: http://localhost:3000/demo/avatar-builder"
echo ""
if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Note: Running in Dev Mode with mock services${NC}"
    echo "      You should see a 'Development Mode' banner in the app."
fi
echo ""
echo "Press Ctrl+C to stop the server."
echo ""

# Wait for the dev server
wait $DEV_PID
