/**
 * Activities Sticker Pack
 *
 * Stickers showing various activities - working, eating, exercising, relaxing, etc.
 */

import {
  Sticker,
  StickerPack,
  StickerCategory,
  Emotion,
  StickerPose,
  Scene,
  StickerProp,
} from '../types';

export const ACTIVITIES_STICKERS: Sticker[] = [
  // Work activities
  {
    id: 'activity_working',
    name: 'Working',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.WORKING,
    scene: Scene.OFFICE,
    props: [StickerProp.LAPTOP],
    tags: ['working', 'busy', 'office', 'computer'],
  },
  {
    id: 'activity_busy',
    name: 'Busy',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.THINKING,
    pose: StickerPose.WORKING,
    scene: Scene.OFFICE,
    props: [StickerProp.LAPTOP],
    textOverlay: 'Busy!',
    tags: ['busy', 'working', 'occupied', 'cant talk'],
  },
  {
    id: 'activity_on_a_call',
    name: 'On a Call',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.OFFICE,
    props: [StickerProp.PHONE],
    textOverlay: 'On a call',
    tags: ['call', 'phone', 'busy', 'meeting'],
  },
  {
    id: 'activity_meeting',
    name: 'In a Meeting',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.SITTING,
    scene: Scene.OFFICE,
    textOverlay: 'In a meeting',
    tags: ['meeting', 'busy', 'work', 'conference'],
  },

  // Food activities
  {
    id: 'activity_eating_pizza',
    name: 'Eating Pizza',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.EATING,
    scene: Scene.HOME,
    props: [StickerProp.PIZZA],
    tags: ['eating', 'pizza', 'food', 'hungry'],
  },
  {
    id: 'activity_eating_burger',
    name: 'Eating Burger',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.EATING,
    scene: Scene.CAFE,
    props: [StickerProp.BURGER],
    tags: ['eating', 'burger', 'food', 'hungry'],
  },
  {
    id: 'activity_drinking_coffee',
    name: 'Drinking Coffee',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.DRINKING,
    scene: Scene.CAFE,
    props: [StickerProp.COFFEE],
    tags: ['coffee', 'drinking', 'morning', 'cafe'],
  },
  {
    id: 'activity_ice_cream',
    name: 'Eating Ice Cream',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.LOVE,
    pose: StickerPose.EATING,
    scene: Scene.OUTDOORS,
    props: [StickerProp.ICE_CREAM],
    tags: ['ice cream', 'eating', 'summer', 'treat'],
  },
  {
    id: 'activity_hungry',
    name: 'Hungry',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.SAD,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fff3e0',
    textOverlay: 'So hungry!',
    isFaceOnly: true,
    tags: ['hungry', 'starving', 'food', 'need to eat'],
  },

  // Relaxation activities
  {
    id: 'activity_chilling',
    name: 'Chilling',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.SITTING,
    scene: Scene.HOME,
    tags: ['chilling', 'relaxing', 'vibing', 'chill'],
  },
  {
    id: 'activity_binging',
    name: 'Binge Watching',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.LYING_DOWN,
    scene: Scene.HOME,
    textOverlay: 'Binging!',
    tags: ['binging', 'watching', 'tv', 'netflix', 'relax'],
  },
  {
    id: 'activity_napping',
    name: 'Napping',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.SLEEPY,
    pose: StickerPose.SLEEPING,
    scene: Scene.HOME,
    props: [StickerProp.ZZZ],
    isFaceOnly: true,
    tags: ['napping', 'sleeping', 'rest', 'tired'],
  },
  {
    id: 'activity_reading',
    name: 'Reading',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.READING,
    scene: Scene.HOME,
    props: [StickerProp.BOOK],
    tags: ['reading', 'book', 'studying', 'learning'],
  },

  // Exercise/Sports activities
  {
    id: 'activity_working_out',
    name: 'Working Out',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.STANDING_HANDS_ON_HIPS,
    scene: Scene.GYM,
    props: [StickerProp.SWEAT_DROP],
    textOverlay: 'Gains!',
    tags: ['workout', 'gym', 'exercise', 'fitness'],
  },
  {
    id: 'activity_running',
    name: 'Running',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.RUNNING,
    scene: Scene.OUTDOORS,
    props: [StickerProp.SWEAT_DROP],
    tags: ['running', 'jogging', 'exercise', 'cardio'],
  },
  {
    id: 'activity_dancing',
    name: 'Dancing',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.DANCING,
    scene: Scene.PARTY,
    props: [StickerProp.SPARKLES],
    tags: ['dancing', 'party', 'music', 'fun'],
  },
  {
    id: 'activity_basketball',
    name: 'Playing Basketball',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.JUMPING,
    scene: Scene.OUTDOORS,
    props: [StickerProp.BASKETBALL],
    tags: ['basketball', 'sports', 'playing', 'ball'],
  },

  // Social activities
  {
    id: 'activity_hanging_out',
    name: 'Hanging Out',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.CAFE,
    textOverlay: 'Hanging out',
    tags: ['hanging out', 'friends', 'social', 'chill'],
  },
  {
    id: 'activity_party',
    name: 'Partying',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.DANCING,
    scene: Scene.PARTY,
    props: [StickerProp.BALLOON, StickerProp.SPARKLES],
    textOverlay: 'Party!',
    tags: ['party', 'dancing', 'celebration', 'fun'],
  },
  {
    id: 'activity_beach',
    name: 'At the Beach',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.BEACH,
    props: [StickerProp.SUN],
    textOverlay: 'Beach day!',
    tags: ['beach', 'summer', 'vacation', 'sun'],
  },

  // Emotional state activities
  {
    id: 'activity_thinking',
    name: 'Thinking',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.THINKING,
    pose: StickerPose.THINKING_POSE,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8eaf6',
    props: [StickerProp.QUESTION_MARK],
    tags: ['thinking', 'pondering', 'considering', 'wondering'],
  },
  {
    id: 'activity_waiting',
    name: 'Waiting',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.STANDING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#eceff1',
    textOverlay: 'Waiting...',
    tags: ['waiting', 'patient', 'bored', 'standing by'],
  },
  {
    id: 'activity_on_my_way',
    name: 'On My Way',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WALKING,
    scene: Scene.CITY,
    textOverlay: 'OMW!',
    tags: ['on my way', 'coming', 'walking', 'traveling'],
  },

  // Status activities
  {
    id: 'activity_brb',
    name: 'Be Right Back',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.WAVING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e0f7fa',
    textOverlay: 'BRB!',
    tags: ['brb', 'be right back', 'away', 'pause'],
  },
  {
    id: 'activity_afk',
    name: 'Away From Keyboard',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.STANDING,
    scene: Scene.OFFICE,
    textOverlay: 'AFK',
    tags: ['afk', 'away', 'not here', 'gaming'],
  },
  {
    id: 'activity_dnd',
    name: 'Do Not Disturb',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.ANNOYED,
    pose: StickerPose.STANDING_ARMS_CROSSED,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffcdd2',
    textOverlay: 'DND!',
    tags: ['do not disturb', 'busy', 'leave me alone', 'focusing'],
  },
  {
    id: 'activity_studying',
    name: 'Studying',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.THINKING,
    pose: StickerPose.READING,
    scene: Scene.OFFICE,
    props: [StickerProp.BOOK],
    textOverlay: 'Studying',
    tags: ['studying', 'learning', 'homework', 'school'],
  },

  // Achievement activities
  {
    id: 'activity_nailed_it',
    name: 'Nailed It!',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.CONFETTI,
    props: [StickerProp.STAR, StickerProp.SPARKLES],
    textOverlay: 'Nailed it!',
    tags: ['nailed it', 'success', 'achievement', 'perfect'],
  },
  {
    id: 'activity_done',
    name: 'Done!',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CONFETTI,
    textOverlay: 'Done!',
    tags: ['done', 'finished', 'complete', 'accomplished'],
  },

  // ========================================================================
  // PHASE 4 EXPANSION - Additional Activities
  // ========================================================================

  // Gaming activities
  {
    id: 'activity_gaming',
    name: 'Gaming',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.SITTING,
    scene: Scene.HOME,
    props: [StickerProp.GAMING_CONTROLLER],
    textOverlay: 'Gaming!',
    tags: ['gaming', 'playing', 'video games', 'gamer'],
  },
  {
    id: 'activity_winning',
    name: 'Winning!',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CONFETTI,
    props: [StickerProp.TROPHY, StickerProp.SPARKLES],
    textOverlay: 'Winner!',
    tags: ['winning', 'victory', 'champion', 'success'],
  },

  // Creative activities
  {
    id: 'activity_music',
    name: 'Making Music',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.CONCERT,
    props: [StickerProp.GUITAR, StickerProp.MUSIC_NOTES],
    tags: ['music', 'playing', 'guitar', 'creative'],
  },
  {
    id: 'activity_singing',
    name: 'Singing',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.STANDING,
    scene: Scene.CONCERT,
    props: [StickerProp.MICROPHONE_PROP, StickerProp.MUSIC_NOTES],
    tags: ['singing', 'karaoke', 'music', 'performance'],
  },
  {
    id: 'activity_taking_photos',
    name: 'Taking Photos',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.OUTDOORS,
    props: [StickerProp.CAMERA],
    textOverlay: 'Cheese!',
    tags: ['photography', 'photos', 'camera', 'selfie'],
  },

  // Food activities
  {
    id: 'activity_boba',
    name: 'Boba Time',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.LOVE,
    pose: StickerPose.DRINKING,
    scene: Scene.CAFE,
    props: [StickerProp.BUBBLE_TEA],
    textOverlay: 'Boba!',
    tags: ['boba', 'bubble tea', 'drinking', 'treat'],
  },
  {
    id: 'activity_sushi',
    name: 'Sushi Time',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.LOVE,
    pose: StickerPose.EATING,
    scene: Scene.RESTAURANT,
    props: [StickerProp.SUSHI],
    tags: ['sushi', 'eating', 'japanese', 'food'],
  },
  {
    id: 'activity_popcorn',
    name: 'Movie Time',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.SITTING,
    scene: Scene.HOME,
    props: [StickerProp.POPCORN],
    textOverlay: 'Movie time!',
    tags: ['movies', 'popcorn', 'watching', 'entertainment'],
  },

  // Outdoor activities
  {
    id: 'activity_hiking',
    name: 'Hiking',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WALKING,
    scene: Scene.MOUNTAIN,
    props: [StickerProp.BACKPACK],
    tags: ['hiking', 'nature', 'outdoors', 'adventure'],
  },
  {
    id: 'activity_camping',
    name: 'Camping',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.SITTING,
    scene: Scene.FOREST,
    props: [StickerProp.FIRE],
    textOverlay: 'Camping!',
    tags: ['camping', 'outdoors', 'nature', 'adventure'],
  },
  {
    id: 'activity_stargazing',
    name: 'Stargazing',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.LOVE,
    pose: StickerPose.LYING_DOWN,
    scene: Scene.NIGHT_SKY,
    props: [StickerProp.STAR, StickerProp.MOON],
    tags: ['stargazing', 'night', 'stars', 'romantic'],
  },
  {
    id: 'activity_sunset',
    name: 'Watching Sunset',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.SUNSET,
    tags: ['sunset', 'view', 'beautiful', 'peaceful'],
  },

  // Travel activities
  {
    id: 'activity_traveling',
    name: 'Traveling',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.STANDING,
    scene: Scene.AIRPORT,
    props: [StickerProp.BACKPACK],
    textOverlay: 'Traveling!',
    tags: ['travel', 'vacation', 'adventure', 'airport'],
  },
  {
    id: 'activity_road_trip',
    name: 'Road Trip',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.SITTING,
    scene: Scene.MOUNTAIN,
    textOverlay: 'Road trip!',
    tags: ['road trip', 'travel', 'driving', 'adventure'],
  },

  // Social activities
  {
    id: 'activity_birthday',
    name: 'Birthday!',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.BIRTHDAY,
    props: [StickerProp.CAKE, StickerProp.BALLOON, StickerProp.PARTY_HAT],
    textOverlay: 'Happy Birthday!',
    tags: ['birthday', 'celebration', 'party', 'cake'],
  },
  {
    id: 'activity_concert',
    name: 'At a Concert',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.DANCING,
    scene: Scene.CONCERT,
    props: [StickerProp.MUSIC_NOTES, StickerProp.SPARKLES],
    tags: ['concert', 'music', 'live', 'dancing'],
  },

  // Sports activities
  {
    id: 'activity_swimming',
    name: 'Swimming',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.SWIMMING_POOL,
    props: [StickerProp.SWEAT_DROP],
    tags: ['swimming', 'pool', 'exercise', 'summer'],
  },
  {
    id: 'activity_yoga',
    name: 'Doing Yoga',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.PARK,
    textOverlay: 'Namaste',
    tags: ['yoga', 'meditation', 'fitness', 'zen'],
  },

  // Weather activities
  {
    id: 'activity_rainy_day',
    name: 'Rainy Day',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.STANDING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#b0bec5',
    props: [StickerProp.UMBRELLA, StickerProp.RAIN],
    tags: ['rain', 'rainy', 'weather', 'umbrella'],
  },
  {
    id: 'activity_snowy_day',
    name: 'Snow Day',
    category: StickerCategory.ACTIVITIES,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CHRISTMAS,
    props: [StickerProp.SNOW_FLAKE],
    textOverlay: 'Snow day!',
    tags: ['snow', 'winter', 'cold', 'holiday'],
  },
];

export const ACTIVITIES_PACK: StickerPack = {
  id: 'activities',
  name: 'Activities',
  description: 'Show what you\'re up to - working, eating, exercising, and more!',
  stickers: ACTIVITIES_STICKERS,
  category: StickerCategory.ACTIVITIES,
  isPremium: false,
};

export default ACTIVITIES_PACK;
