/**
 * Celebrations Sticker Pack
 *
 * Stickers for celebrations, parties, achievements, and special occasions.
 * Uses enhanced props like confetti, fireworks, multiple hearts/stars, etc.
 */

import {
  Sticker,
  StickerPack,
  StickerCategory,
  Emotion,
  StickerPose,
  Scene,
  StickerProp,
} from '../types';

export const CELEBRATIONS_STICKERS: Sticker[] = [
  // Party and Celebration
  {
    id: 'celebrate_party',
    name: 'Party Time!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CONFETTI,
    props: [StickerProp.STREAMERS, StickerProp.BALLOONS],
    textOverlay: 'Party!',
    tags: ['party', 'celebrate', 'celebration', 'fun', 'confetti'],
  },
  {
    id: 'celebrate_fireworks',
    name: 'Fireworks!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.WAVING,
    scene: Scene.NIGHT_SKY,
    props: [StickerProp.FIREWORKS],
    textOverlay: 'Wow!',
    tags: ['fireworks', 'celebrate', 'new year', 'celebration', 'night'],
  },
  {
    id: 'celebrate_balloons',
    name: 'Balloon Party',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.JUMPING,
    scene: Scene.PARTY,
    props: [StickerProp.BALLOONS, StickerProp.STREAMERS],
    tags: ['balloons', 'party', 'birthday', 'celebration', 'fun'],
  },
  {
    id: 'celebrate_presents',
    name: 'Gift Time!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.STANDING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8f5e9',
    props: [StickerProp.PRESENTS, StickerProp.SPARKLES],
    textOverlay: 'For You!',
    tags: ['gift', 'present', 'birthday', 'christmas', 'surprise'],
  },
  {
    id: 'celebrate_confetti',
    name: 'Confetti!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.LAUGHING,
    pose: StickerPose.DANCING,
    scene: Scene.CONFETTI,
    props: [StickerProp.STREAMERS],
    textOverlay: 'Yay!',
    tags: ['confetti', 'party', 'celebrate', 'yay', 'happy'],
  },

  // Achievement and Success
  {
    id: 'celebrate_champion',
    name: 'Champion!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.STARS,
    props: [StickerProp.STARS_MULTIPLE, StickerProp.GLOW],
    textOverlay: 'Champion!',
    tags: ['champion', 'winner', 'victory', 'achievement', 'success'],
  },
  {
    id: 'celebrate_nailed_it',
    name: 'Nailed It!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.GRADIENT,
    sceneColor: '#c5e1a5',
    props: [StickerProp.SPARKLES, StickerProp.CHECK_MARK],
    textOverlay: 'Nailed It!',
    tags: ['success', 'nailed it', 'achievement', 'done', 'accomplished'],
  },
  {
    id: 'celebrate_level_up',
    name: 'Level Up!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.JUMPING,
    scene: Scene.STARS,
    props: [StickerProp.STARS_MULTIPLE, StickerProp.GLOW],
    textOverlay: 'Level Up!',
    tags: ['level up', 'achievement', 'gaming', 'progress', 'milestone'],
  },
  {
    id: 'celebrate_genius',
    name: 'Genius!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.POINTING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fff8e1',
    props: [StickerProp.GLOW, StickerProp.SPARKLES],
    textOverlay: 'Genius!',
    tags: ['genius', 'smart', 'brilliant', 'clever', 'idea'],
  },

  // Love and Hearts
  {
    id: 'celebrate_love_hearts',
    name: 'So Much Love',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.STANDING,
    scene: Scene.HEARTS,
    props: [StickerProp.HEARTS_MULTIPLE],
    tags: ['love', 'hearts', 'adore', 'romantic', 'sweet'],
  },
  {
    id: 'celebrate_heart_eyes',
    name: 'Heart Eyes',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART_EYES, StickerProp.HEARTS_MULTIPLE],
    textOverlay: 'OMG!',
    tags: ['love', 'heart eyes', 'crush', 'adore', 'cute'],
  },
  {
    id: 'celebrate_angel',
    name: 'Angel',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.CLOUDS,
    props: [StickerProp.ANGEL_HALO, StickerProp.ANGEL_WINGS, StickerProp.GLOW],
    tags: ['angel', 'innocent', 'good', 'pure', 'heavenly'],
  },

  // Birthday
  {
    id: 'celebrate_birthday',
    name: 'Happy Birthday!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.PARTY,
    props: [StickerProp.BALLOONS, StickerProp.PRESENTS, StickerProp.STREAMERS],
    textOverlay: 'Happy Birthday!',
    tags: ['birthday', 'celebration', 'party', 'cake', 'presents'],
  },
  {
    id: 'celebrate_make_wish',
    name: 'Make a Wish!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.STANDING,
    scene: Scene.STARS,
    props: [StickerProp.SPARKLES, StickerProp.STARS_MULTIPLE],
    textOverlay: 'Make a Wish!',
    tags: ['birthday', 'wish', 'candles', 'celebration'],
  },

  // New Year / Holiday
  {
    id: 'celebrate_new_year',
    name: 'Happy New Year!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.NIGHT_SKY,
    props: [StickerProp.FIREWORKS, StickerProp.STREAMERS],
    textOverlay: 'Happy New Year!',
    tags: ['new year', 'celebration', 'fireworks', 'midnight', 'countdown'],
  },
  {
    id: 'celebrate_countdown',
    name: 'Countdown!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.JUMPING,
    scene: Scene.PARTY,
    props: [StickerProp.SPARKLES, StickerProp.STARS_MULTIPLE],
    textOverlay: '3...2...1!',
    tags: ['countdown', 'new year', 'anticipation', 'excitement'],
  },

  // Fun and Mischief
  {
    id: 'celebrate_devil',
    name: 'Little Devil',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.WINK,
    pose: StickerPose.STANDING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffcdd2',
    props: [StickerProp.DEVIL_HORNS, StickerProp.DEVIL_TAIL],
    textOverlay: 'Oops!',
    tags: ['devil', 'mischief', 'naughty', 'playful', 'trouble'],
  },
  {
    id: 'celebrate_alien',
    name: 'Out of This World!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.PEACE_SIGN,
    scene: Scene.SPACE,
    props: [StickerProp.ALIEN, StickerProp.STARS_MULTIPLE],
    textOverlay: 'Awesome!',
    tags: ['alien', 'space', 'cool', 'amazing', 'out of this world'],
  },

  // Appreciation
  {
    id: 'celebrate_thank_you',
    name: 'Thank You!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WAVING,
    scene: Scene.GRADIENT,
    sceneColor: '#e1bee7',
    props: [StickerProp.HEARTS_MULTIPLE, StickerProp.SPARKLES],
    textOverlay: 'Thank You!',
    tags: ['thank you', 'thanks', 'gratitude', 'appreciation', 'grateful'],
  },
  {
    id: 'celebrate_youre_awesome',
    name: "You're Awesome!",
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.POINTING,
    scene: Scene.STARS,
    props: [StickerProp.STARS_MULTIPLE, StickerProp.GLOW],
    textOverlay: "You're Awesome!",
    tags: ['awesome', 'appreciation', 'compliment', 'positive', 'encouragement'],
  },
  {
    id: 'celebrate_crush_it',
    name: 'Crush It!',
    category: StickerCategory.CELEBRATIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.GRADIENT,
    sceneColor: '#ffcc80',
    props: [StickerProp.FIRE, StickerProp.SPARKLES],
    textOverlay: 'Crush It!',
    tags: ['crush it', 'motivation', 'encouragement', 'success', 'go for it'],
  },
];

export const CELEBRATIONS_PACK: StickerPack = {
  id: 'celebrations',
  name: 'Celebrations',
  description: 'Party, achievements, and special occasions',
  category: StickerCategory.CELEBRATIONS,
  stickers: CELEBRATIONS_STICKERS,
};

export default CELEBRATIONS_STICKERS;
