/**
 * Emotions Sticker Pack
 *
 * Stickers expressing various emotions - happy, sad, angry, love, etc.
 */

import {
  Sticker,
  StickerPack,
  StickerCategory,
  Emotion,
  StickerPose,
  Scene,
  StickerProp,
} from '../types';

export const EMOTIONS_STICKERS: Sticker[] = [
  // Happy emotions
  {
    id: 'emotion_happy',
    name: 'Happy',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.GRADIENT,
    sceneColor: '#fff9c4',
    props: [StickerProp.SPARKLES],
    isFaceOnly: true,
    tags: ['happy', 'smile', 'joy', 'positive'],
  },
  {
    id: 'emotion_so_happy',
    name: 'So Happy!',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.JUMPING,
    scene: Scene.CONFETTI,
    props: [StickerProp.SPARKLES],
    textOverlay: 'So happy!',
    tags: ['happy', 'excited', 'joy', 'ecstatic'],
  },
  {
    id: 'emotion_yay',
    name: 'Yay!',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.PARTY,
    textOverlay: 'Yay!',
    tags: ['yay', 'excited', 'celebration', 'happy'],
  },
  {
    id: 'emotion_content',
    name: 'Content',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8f5e9',
    isFaceOnly: true,
    tags: ['content', 'peaceful', 'calm', 'satisfied'],
  },

  // Laughing emotions
  {
    id: 'emotion_laughing',
    name: 'Laughing',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LAUGHING,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.GRADIENT,
    sceneColor: '#fff59d',
    props: [StickerProp.TEARS],
    isFaceOnly: true,
    tags: ['laughing', 'lol', 'funny', 'haha'],
  },
  {
    id: 'emotion_lol',
    name: 'LOL',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LAUGHING,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffecb3',
    props: [StickerProp.TEARS],
    textOverlay: 'LOL',
    isFaceOnly: true,
    tags: ['lol', 'laughing', 'funny', 'hilarious'],
  },
  {
    id: 'emotion_dying',
    name: 'Dying of Laughter',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LAUGHING,
    pose: StickerPose.LYING_DOWN,
    scene: Scene.GRADIENT,
    sceneColor: '#ffe082',
    props: [StickerProp.TEARS],
    textOverlay: 'Dead!',
    tags: ['dying', 'laughing', 'hilarious', 'cant breathe'],
  },
  {
    id: 'emotion_hehe',
    name: 'Hehe',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.WINK,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fce4ec',
    textOverlay: 'Hehe',
    isFaceOnly: true,
    tags: ['hehe', 'giggle', 'mischievous', 'playful'],
  },

  // Love emotions
  {
    id: 'emotion_in_love',
    name: 'In Love',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART],
    isFaceOnly: true,
    tags: ['love', 'hearts', 'adore', 'romantic'],
  },
  {
    id: 'emotion_love_it',
    name: 'Love It!',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.HEART_HANDS,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART, StickerProp.SPARKLES],
    textOverlay: 'Love it!',
    tags: ['love', 'like', 'adore', 'favorite'],
  },
  {
    id: 'emotion_crushing',
    name: 'Crushing Hard',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART],
    isFaceOnly: true,
    tags: ['crush', 'love', 'smitten', 'infatuated'],
  },
  {
    id: 'emotion_kiss',
    name: 'Kiss',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART],
    isFaceOnly: true,
    tags: ['kiss', 'love', 'mwah', 'affection'],
  },

  // Sad emotions
  {
    id: 'emotion_sad',
    name: 'Sad',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SAD,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e3f2fd',
    isFaceOnly: true,
    tags: ['sad', 'unhappy', 'down', 'blue'],
  },
  {
    id: 'emotion_crying',
    name: 'Crying',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.CRYING,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.GRADIENT,
    sceneColor: '#bbdefb',
    props: [StickerProp.TEARS],
    isFaceOnly: true,
    tags: ['crying', 'sad', 'tears', 'upset'],
  },
  {
    id: 'emotion_sobbing',
    name: 'Sobbing',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.CRYING,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#90caf9',
    props: [StickerProp.TEARS],
    textOverlay: 'Why?!',
    isFaceOnly: true,
    tags: ['sobbing', 'crying', 'devastated', 'heartbroken'],
  },
  {
    id: 'emotion_feeling_down',
    name: 'Feeling Down',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SAD,
    pose: StickerPose.SITTING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#cfd8dc',
    tags: ['down', 'sad', 'depressed', 'low'],
  },

  // Angry emotions
  {
    id: 'emotion_angry',
    name: 'Angry',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.ANGRY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.GRADIENT,
    sceneColor: '#ffcdd2',
    props: [StickerProp.ANGER_VEIN],
    isFaceOnly: true,
    tags: ['angry', 'mad', 'furious', 'upset'],
  },
  {
    id: 'emotion_furious',
    name: 'Furious',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.ANGRY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ef9a9a',
    props: [StickerProp.ANGER_VEIN, StickerProp.FIRE],
    isFaceOnly: true,
    tags: ['furious', 'rage', 'angry', 'livid'],
  },
  {
    id: 'emotion_grr',
    name: 'Grr!',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.ANGRY,
    pose: StickerPose.STANDING_ARMS_CROSSED,
    scene: Scene.GRADIENT,
    sceneColor: '#ffab91',
    props: [StickerProp.ANGER_VEIN],
    textOverlay: 'Grr!',
    tags: ['grr', 'angry', 'frustrated', 'mad'],
  },

  // Cool/Confident emotions
  {
    id: 'emotion_cool',
    name: 'Cool',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.PEACE_SIGN,
    scene: Scene.GRADIENT,
    sceneColor: '#b3e5fc',
    props: [StickerProp.SPARKLES],
    tags: ['cool', 'chill', 'awesome', 'swag'],
  },
  {
    id: 'emotion_feeling_myself',
    name: 'Feeling Myself',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.STANDING_HANDS_ON_HIPS,
    scene: Scene.STARS,
    props: [StickerProp.SPARKLES, StickerProp.STAR],
    tags: ['confident', 'self love', 'feeling good', 'empowered'],
  },
  {
    id: 'emotion_boss',
    name: 'Boss Mode',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.STANDING_ARMS_CROSSED,
    scene: Scene.CITY,
    textOverlay: 'Boss!',
    tags: ['boss', 'confident', 'powerful', 'leader'],
  },

  // Tired/Sleepy emotions
  {
    id: 'emotion_tired',
    name: 'Tired',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SLEEPY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e1bee7',
    props: [StickerProp.ZZZ],
    isFaceOnly: true,
    tags: ['tired', 'sleepy', 'exhausted', 'drained'],
  },
  {
    id: 'emotion_need_coffee',
    name: 'Need Coffee',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SLEEPY,
    pose: StickerPose.DRINKING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#d7ccc8',
    props: [StickerProp.COFFEE],
    textOverlay: 'Need coffee',
    tags: ['tired', 'coffee', 'morning', 'sleepy'],
  },
  {
    id: 'emotion_exhausted',
    name: 'Exhausted',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SLEEPY,
    pose: StickerPose.LYING_DOWN,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#d1c4e9',
    props: [StickerProp.ZZZ],
    textOverlay: 'So tired...',
    tags: ['exhausted', 'drained', 'worn out', 'done'],
  },

  // Nervous/Anxious emotions
  {
    id: 'emotion_nervous',
    name: 'Nervous',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.NERVOUS,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffe0b2',
    props: [StickerProp.SWEAT_DROP],
    isFaceOnly: true,
    tags: ['nervous', 'anxious', 'worried', 'scared'],
  },
  {
    id: 'emotion_stressed',
    name: 'Stressed',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.NERVOUS,
    pose: StickerPose.FACEPALM,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffccbc',
    props: [StickerProp.SWEAT_DROP, StickerProp.LIGHTNING],
    textOverlay: 'Stressed!',
    tags: ['stressed', 'anxious', 'overwhelmed', 'pressure'],
  },

  // Surprised/Shocked emotions
  {
    id: 'emotion_surprised',
    name: 'Surprised',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SURPRISED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.GRADIENT,
    sceneColor: '#e1f5fe',
    props: [StickerProp.EXCLAMATION],
    isFaceOnly: true,
    tags: ['surprised', 'shocked', 'wow', 'unexpected'],
  },
  {
    id: 'emotion_shook',
    name: 'Shook',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SHOCKED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#b3e5fc',
    props: [StickerProp.LIGHTNING],
    textOverlay: 'Shook!',
    isFaceOnly: true,
    tags: ['shook', 'shocked', 'stunned', 'disbelief'],
  },

  // ========================================================================
  // PHASE 4 EXPANSION - Additional Emotions
  // ========================================================================

  // Confused emotions
  {
    id: 'emotion_confused',
    name: 'Confused',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.CONFUSED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8eaf6',
    props: [StickerProp.QUESTION_MARK],
    isFaceOnly: true,
    tags: ['confused', 'puzzled', 'bewildered', 'uncertain'],
  },
  {
    id: 'emotion_huh',
    name: 'Huh?',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.CONFUSED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#d1c4e9',
    props: [StickerProp.QUESTION_MARK],
    textOverlay: 'Huh?',
    isFaceOnly: true,
    tags: ['huh', 'confused', 'what', 'lost'],
  },
  {
    id: 'emotion_skeptical',
    name: 'Skeptical',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SKEPTICAL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#efebe9',
    isFaceOnly: true,
    tags: ['skeptical', 'doubtful', 'suspicious', 'unsure'],
  },

  // Embarrassed emotions
  {
    id: 'emotion_embarrassed',
    name: 'Embarrassed',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.EMBARRASSED,
    pose: StickerPose.FACEPALM,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffcdd2',
    props: [StickerProp.SWEAT_DROP],
    tags: ['embarrassed', 'ashamed', 'cringe', 'mortified'],
  },
  {
    id: 'emotion_facepalm',
    name: 'Facepalm',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.EMBARRASSED,
    pose: StickerPose.FACEPALM,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffe0b2',
    textOverlay: 'Ugh',
    tags: ['facepalm', 'embarrassed', 'cringe', 'really'],
  },

  // Sick emotions
  {
    id: 'emotion_sick',
    name: 'Sick',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SICK,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#c8e6c9',
    props: [StickerProp.SWEAT_DROP],
    isFaceOnly: true,
    tags: ['sick', 'ill', 'unwell', 'nauseous'],
  },
  {
    id: 'emotion_not_feeling_well',
    name: 'Not Feeling Well',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.SICK,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#dcedc8',
    textOverlay: 'Not well...',
    isFaceOnly: true,
    tags: ['sick', 'under the weather', 'ill', 'unwell'],
  },

  // Neutral/Bored emotions
  {
    id: 'emotion_meh',
    name: 'Meh',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#eeeeee',
    textOverlay: 'Meh',
    isFaceOnly: true,
    tags: ['meh', 'bored', 'indifferent', 'whatever'],
  },
  {
    id: 'emotion_bored',
    name: 'Bored',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e0e0e0',
    isFaceOnly: true,
    tags: ['bored', 'uninterested', 'dull', 'meh'],
  },
  {
    id: 'emotion_shrug',
    name: 'Shrug',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.SHRUG,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#f5f5f5',
    tags: ['shrug', 'idk', 'whatever', 'indifferent'],
  },

  // Seasonal emotions
  {
    id: 'emotion_spooky',
    name: 'Spooky',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HALLOWEEN,
    props: [StickerProp.GHOST],
    textOverlay: 'Boo!',
    isFaceOnly: true,
    tags: ['spooky', 'halloween', 'scary', 'boo'],
  },
  {
    id: 'emotion_festive',
    name: 'Festive',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CHRISTMAS,
    props: [StickerProp.SPARKLES],
    textOverlay: 'Tis the season!',
    tags: ['festive', 'christmas', 'holiday', 'celebration'],
  },
  {
    id: 'emotion_valentines',
    name: 'Be Mine',
    category: StickerCategory.EMOTIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.HEART_HANDS,
    scene: Scene.VALENTINES,
    props: [StickerProp.HEART],
    textOverlay: 'Be mine!',
    tags: ['valentines', 'love', 'romantic', 'hearts'],
  },
];

export const EMOTIONS_PACK: StickerPack = {
  id: 'emotions',
  name: 'Emotions',
  description: 'Express how you really feel with these emotional stickers!',
  stickers: EMOTIONS_STICKERS,
  category: StickerCategory.EMOTIONS,
  isPremium: false,
};

export default EMOTIONS_PACK;
