/**
 * Greetings Sticker Pack
 *
 * Stickers for saying hello, goodbye, thank you, and other greetings.
 */

import {
  Sticker,
  StickerPack,
  StickerCategory,
  Emotion,
  StickerPose,
  Scene,
  StickerProp,
} from '../types';

export const GREETINGS_STICKERS: Sticker[] = [
  // Hello/Hi stickers
  {
    id: 'greeting_wave_hi',
    name: 'Hi!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WAVING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e3f2fd',
    textOverlay: 'Hi!',
    tags: ['hello', 'hi', 'wave', 'greeting', 'friendly'],
  },
  {
    id: 'greeting_wave_hello',
    name: 'Hello!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.WAVING,
    scene: Scene.CONFETTI,
    textOverlay: 'Hello!',
    tags: ['hello', 'hi', 'wave', 'greeting', 'excited'],
  },
  {
    id: 'greeting_wave_hey',
    name: 'Hey!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WAVING,
    scene: Scene.GRADIENT,
    sceneColor: '#fff9c4',
    textOverlay: 'Hey!',
    tags: ['hey', 'hi', 'wave', 'casual', 'greeting'],
  },
  {
    id: 'greeting_peace_sign',
    name: 'Peace',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.COOL,
    pose: StickerPose.PEACE_SIGN,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8f5e9',
    tags: ['peace', 'hello', 'cool', 'chill', 'greeting'],
  },
  {
    id: 'greeting_excited_hello',
    name: 'Excited Hello',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.JUMPING,
    scene: Scene.STARS,
    props: [StickerProp.SPARKLES],
    textOverlay: 'Hey there!',
    tags: ['hello', 'excited', 'enthusiastic', 'greeting'],
  },

  // Goodbye stickers
  {
    id: 'greeting_bye',
    name: 'Bye!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WAVING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fce4ec',
    textOverlay: 'Bye!',
    tags: ['bye', 'goodbye', 'farewell', 'wave', 'leaving'],
  },
  {
    id: 'greeting_see_ya',
    name: 'See Ya!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.WINK,
    pose: StickerPose.PEACE_SIGN,
    scene: Scene.GRADIENT,
    sceneColor: '#e1bee7',
    textOverlay: 'See ya!',
    tags: ['bye', 'see you', 'later', 'farewell', 'casual'],
  },
  {
    id: 'greeting_later',
    name: 'Later!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.COOL,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fff3e0',
    textOverlay: 'Later!',
    tags: ['bye', 'later', 'see you', 'casual', 'chill'],
  },
  {
    id: 'greeting_goodbye_sad',
    name: 'Sad Goodbye',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.SAD,
    pose: StickerPose.WAVING,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e0e0e0',
    textOverlay: 'Bye...',
    tags: ['bye', 'goodbye', 'sad', 'miss you', 'farewell'],
  },

  // Thank you stickers
  {
    id: 'greeting_thanks',
    name: 'Thanks!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.HEARTS,
    textOverlay: 'Thanks!',
    tags: ['thanks', 'thank you', 'grateful', 'appreciation'],
  },
  {
    id: 'greeting_thank_you',
    name: 'Thank You',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.LOVE,
    pose: StickerPose.HEART_HANDS,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART],
    textOverlay: 'Thank you!',
    tags: ['thank you', 'grateful', 'appreciation', 'love'],
  },
  {
    id: 'greeting_thanks_so_much',
    name: 'Thanks So Much',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CONFETTI,
    props: [StickerProp.SPARKLES],
    textOverlay: 'Thanks so much!',
    tags: ['thanks', 'grateful', 'excited', 'appreciation'],
  },

  // Please stickers
  {
    id: 'greeting_please',
    name: 'Please',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8eaf6',
    textOverlay: 'Please?',
    isFaceOnly: true,
    tags: ['please', 'request', 'polite', 'asking'],
  },
  {
    id: 'greeting_pretty_please',
    name: 'Pretty Please',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.LOVE,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HEARTS,
    props: [StickerProp.SPARKLES],
    textOverlay: 'Pretty please?',
    isFaceOnly: true,
    tags: ['please', 'cute', 'request', 'asking', 'polite'],
  },

  // Welcome stickers
  {
    id: 'greeting_welcome',
    name: 'Welcome!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WAVING,
    scene: Scene.CONFETTI,
    textOverlay: 'Welcome!',
    tags: ['welcome', 'greeting', 'hello', 'hospitality'],
  },
  {
    id: 'greeting_welcome_party',
    name: 'Welcome Party',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.PARTY,
    props: [StickerProp.BALLOON],
    textOverlay: 'Welcome!',
    tags: ['welcome', 'party', 'celebration', 'greeting'],
  },

  // Good morning/night stickers
  {
    id: 'greeting_good_morning',
    name: 'Good Morning',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.WAVING,
    scene: Scene.GRADIENT,
    sceneColor: '#fff8e1',
    props: [StickerProp.SUN],
    textOverlay: 'Good morning!',
    tags: ['morning', 'greeting', 'wake up', 'hello'],
  },
  {
    id: 'greeting_good_night',
    name: 'Good Night',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.SLEEPY,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.STARS,
    props: [StickerProp.ZZZ, StickerProp.MOON],
    textOverlay: 'Good night!',
    isFaceOnly: true,
    tags: ['night', 'goodbye', 'sleep', 'bedtime'],
  },
  {
    id: 'greeting_sweet_dreams',
    name: 'Sweet Dreams',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.SLEEPING,
    scene: Scene.STARS,
    props: [StickerProp.ZZZ],
    textOverlay: 'Sweet dreams!',
    isFaceOnly: true,
    tags: ['dreams', 'sleep', 'night', 'goodnight'],
  },

  // Miss you stickers
  {
    id: 'greeting_miss_you',
    name: 'Miss You',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.SAD,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART],
    textOverlay: 'Miss you!',
    isFaceOnly: true,
    tags: ['miss', 'love', 'sad', 'longing'],
  },
  {
    id: 'greeting_thinking_of_you',
    name: 'Thinking of You',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.LOVE,
    pose: StickerPose.THINKING_POSE,
    scene: Scene.HEARTS,
    props: [StickerProp.HEART],
    textOverlay: 'Thinking of you',
    tags: ['thinking', 'miss', 'love', 'care'],
  },

  // Congratulations stickers
  {
    id: 'greeting_congrats',
    name: 'Congrats!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CONFETTI,
    props: [StickerProp.SPARKLES],
    textOverlay: 'Congrats!',
    tags: ['congratulations', 'celebration', 'success', 'achievement'],
  },
  {
    id: 'greeting_well_done',
    name: 'Well Done',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.STARS,
    props: [StickerProp.STAR],
    textOverlay: 'Well done!',
    tags: ['congratulations', 'good job', 'achievement', 'proud'],
  },
  {
    id: 'greeting_you_did_it',
    name: 'You Did It!',
    category: StickerCategory.GREETINGS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.JUMPING,
    scene: Scene.PARTY,
    props: [StickerProp.SPARKLES, StickerProp.BALLOON],
    textOverlay: 'You did it!',
    tags: ['congratulations', 'success', 'celebration', 'achievement'],
  },
];

export const GREETINGS_PACK: StickerPack = {
  id: 'greetings',
  name: 'Greetings',
  description: 'Say hello, goodbye, thank you, and more!',
  stickers: GREETINGS_STICKERS,
  category: StickerCategory.GREETINGS,
  isPremium: false,
};

export default GREETINGS_PACK;
