/**
 * Reactions Sticker Pack
 *
 * Stickers for reacting to messages - yes, no, wow, agreement, disagreement, etc.
 */

import {
  Sticker,
  StickerPack,
  StickerCategory,
  Emotion,
  StickerPose,
  Scene,
  StickerProp,
} from '../types';

export const REACTIONS_STICKERS: Sticker[] = [
  // Positive reactions
  {
    id: 'reaction_thumbs_up',
    name: 'Thumbs Up',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8f5e9',
    tags: ['yes', 'agree', 'good', 'thumbs up', 'positive'],
  },
  {
    id: 'reaction_yes',
    name: 'Yes!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.GRADIENT,
    sceneColor: '#c8e6c9',
    textOverlay: 'Yes!',
    tags: ['yes', 'agree', 'positive', 'affirmative'],
  },
  {
    id: 'reaction_absolutely',
    name: 'Absolutely!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.CELEBRATING,
    scene: Scene.CONFETTI,
    textOverlay: 'Absolutely!',
    tags: ['yes', 'definitely', 'agree', 'enthusiastic'],
  },
  {
    id: 'reaction_ok',
    name: 'OK!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.OK_SIGN,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e3f2fd',
    textOverlay: 'OK!',
    tags: ['ok', 'okay', 'agree', 'good', 'fine'],
  },
  {
    id: 'reaction_perfect',
    name: 'Perfect!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.LOVE,
    pose: StickerPose.OK_SIGN,
    scene: Scene.STARS,
    props: [StickerProp.SPARKLES],
    textOverlay: 'Perfect!',
    tags: ['perfect', 'great', 'excellent', 'amazing'],
  },
  {
    id: 'reaction_great',
    name: 'Great!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.HAPPY,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.GRADIENT,
    sceneColor: '#fff9c4',
    textOverlay: 'Great!',
    tags: ['great', 'good', 'positive', 'agreement'],
  },

  // Negative reactions
  {
    id: 'reaction_thumbs_down',
    name: 'Thumbs Down',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.ANNOYED,
    pose: StickerPose.THUMBS_DOWN,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffebee',
    tags: ['no', 'disagree', 'bad', 'thumbs down', 'negative'],
  },
  {
    id: 'reaction_no',
    name: 'No!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.ANGRY,
    pose: StickerPose.STANDING_ARMS_CROSSED,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffcdd2',
    textOverlay: 'No!',
    tags: ['no', 'disagree', 'negative', 'refuse'],
  },
  {
    id: 'reaction_nope',
    name: 'Nope',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.ANNOYED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#eeeeee',
    textOverlay: 'Nope',
    isFaceOnly: true,
    tags: ['no', 'nope', 'disagree', 'casual'],
  },
  {
    id: 'reaction_not_gonna_happen',
    name: 'Not Gonna Happen',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.SKEPTICAL,
    pose: StickerPose.STANDING_ARMS_CROSSED,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e0e0e0',
    textOverlay: 'Nah',
    tags: ['no', 'refuse', 'reject', 'never'],
  },

  // Surprise reactions
  {
    id: 'reaction_wow',
    name: 'Wow!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.SURPRISED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.GRADIENT,
    sceneColor: '#e1f5fe',
    props: [StickerProp.SPARKLES],
    textOverlay: 'Wow!',
    isFaceOnly: true,
    tags: ['wow', 'surprised', 'amazed', 'shocked'],
  },
  {
    id: 'reaction_omg',
    name: 'OMG!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.SHOCKED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fff8e1',
    props: [StickerProp.EXCLAMATION],
    textOverlay: 'OMG!',
    isFaceOnly: true,
    tags: ['omg', 'shocked', 'surprised', 'disbelief'],
  },
  {
    id: 'reaction_what',
    name: 'What?!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.CONFUSED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ede7f6',
    props: [StickerProp.QUESTION_MARK],
    textOverlay: 'What?!',
    isFaceOnly: true,
    tags: ['what', 'confused', 'surprised', 'question'],
  },
  {
    id: 'reaction_mind_blown',
    name: 'Mind Blown',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.SHOCKED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SPACE,
    props: [StickerProp.SPARKLES, StickerProp.LIGHTNING],
    isFaceOnly: true,
    tags: ['mind blown', 'shocked', 'amazed', 'incredible'],
  },

  // Thinking/Uncertain reactions
  {
    id: 'reaction_hmm',
    name: 'Hmm...',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.THINKING,
    pose: StickerPose.THINKING_POSE,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#f5f5f5',
    textOverlay: 'Hmm...',
    tags: ['thinking', 'hmm', 'uncertain', 'pondering'],
  },
  {
    id: 'reaction_idk',
    name: "I Don't Know",
    category: StickerCategory.REACTIONS,
    emotion: Emotion.CONFUSED,
    pose: StickerPose.SHRUG,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8eaf6',
    props: [StickerProp.QUESTION_MARK],
    textOverlay: 'IDK',
    tags: ['idk', 'dont know', 'shrug', 'uncertain'],
  },
  {
    id: 'reaction_maybe',
    name: 'Maybe',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.SKEPTICAL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#fff3e0',
    textOverlay: 'Maybe...',
    isFaceOnly: true,
    tags: ['maybe', 'uncertain', 'possibly', 'unsure'],
  },
  {
    id: 'reaction_sure',
    name: 'Sure',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.THUMBS_UP,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e0f7fa',
    textOverlay: 'Sure',
    tags: ['sure', 'okay', 'fine', 'agreement'],
  },

  // Agreement/Disagreement
  {
    id: 'reaction_same',
    name: 'Same!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.EXCITED,
    pose: StickerPose.POINTING,
    scene: Scene.GRADIENT,
    sceneColor: '#bbdefb',
    textOverlay: 'Same!',
    tags: ['same', 'agree', 'relate', 'me too'],
  },
  {
    id: 'reaction_mood',
    name: 'Mood',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.NEUTRAL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e8eaf6',
    textOverlay: 'Mood',
    isFaceOnly: true,
    tags: ['mood', 'relate', 'same', 'vibe'],
  },
  {
    id: 'reaction_facts',
    name: 'Facts!',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.COOL,
    pose: StickerPose.POINTING,
    scene: Scene.GRADIENT,
    sceneColor: '#c5cae9',
    textOverlay: 'Facts!',
    tags: ['facts', 'true', 'agree', 'real'],
  },

  // Facepalm/Embarrassment reactions
  {
    id: 'reaction_facepalm',
    name: 'Facepalm',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.EMBARRASSED,
    pose: StickerPose.FACEPALM,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffecb3',
    props: [StickerProp.SWEAT_DROP],
    tags: ['facepalm', 'embarrassed', 'cringe', 'sigh'],
  },
  {
    id: 'reaction_oh_no',
    name: 'Oh No',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.EMBARRASSED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffcdd2',
    textOverlay: 'Oh no...',
    isFaceOnly: true,
    tags: ['oh no', 'embarrassed', 'mistake', 'oops'],
  },
  {
    id: 'reaction_yikes',
    name: 'Yikes',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.NERVOUS,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#ffe0b2',
    props: [StickerProp.SWEAT_DROP],
    textOverlay: 'Yikes',
    isFaceOnly: true,
    tags: ['yikes', 'awkward', 'cringe', 'nervous'],
  },

  // Eye roll/Annoyed reactions
  {
    id: 'reaction_eye_roll',
    name: 'Eye Roll',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.ANNOYED,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#e0e0e0',
    isFaceOnly: true,
    tags: ['eye roll', 'annoyed', 'whatever', 'sarcastic'],
  },
  {
    id: 'reaction_seriously',
    name: 'Seriously?',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.SKEPTICAL,
    pose: StickerPose.FACE_ONLY,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#eceff1',
    textOverlay: 'Seriously?',
    isFaceOnly: true,
    tags: ['seriously', 'skeptical', 'really', 'doubt'],
  },
  {
    id: 'reaction_really',
    name: 'Really?',
    category: StickerCategory.REACTIONS,
    emotion: Emotion.ANNOYED,
    pose: StickerPose.STANDING_ARMS_CROSSED,
    scene: Scene.SOLID_COLOR,
    sceneColor: '#cfd8dc',
    textOverlay: 'Really?',
    tags: ['really', 'disbelief', 'annoyed', 'skeptical'],
  },
];

export const REACTIONS_PACK: StickerPack = {
  id: 'reactions',
  name: 'Reactions',
  description: 'React to anything with thumbs up, thumbs down, wow, and more!',
  stickers: REACTIONS_STICKERS,
  category: StickerCategory.REACTIONS,
  isPremium: false,
};

export default REACTIONS_PACK;
