#!/bin/bash
# Build the webgl-avatar R3F bundle to a single HTML file
# Output: assets/webgl/avatar-bundle.html and components/avatar3d/r3fBundle.ts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WEBGL_DIR="$PROJECT_ROOT/webgl-avatar"
OUTPUT_DIR="$PROJECT_ROOT/assets/webgl"
R3F_BUNDLE_TS="$PROJECT_ROOT/components/avatar3d/r3fBundle.ts"

echo "Building webgl-avatar R3F bundle..."

# Navigate to webgl-avatar directory
cd "$WEBGL_DIR"

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
  echo "Installing dependencies..."
  npm install
fi

# Build the bundle
echo "Building bundle..."
npm run build

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Copy the built file
echo "Copying bundle to $OUTPUT_DIR..."
cp "$WEBGL_DIR/dist/index.html" "$OUTPUT_DIR/avatar-bundle.html"

# Update the r3fBundle.ts file with the actual bundle content
echo "Updating $R3F_BUNDLE_TS..."
BUNDLE_CONTENT=$(cat "$WEBGL_DIR/dist/index.html")

# Escape backticks and ${} for template literal
ESCAPED_CONTENT=$(echo "$BUNDLE_CONTENT" | sed 's/`/\\`/g' | sed 's/\${/\\${/g')

cat > "$R3F_BUNDLE_TS" << 'HEADER'
/**
 * R3F Bundle HTML Content
 *
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY!
 * Generated by: npm run build:webgl
 *
 * This file contains the bundled React Three Fiber avatar renderer.
 * It includes React, Three.js, React Three Fiber, and @react-three/drei.
 */

export const R3F_BUNDLE_HTML = `
HEADER

echo "$BUNDLE_CONTENT" >> "$R3F_BUNDLE_TS"

echo '`;' >> "$R3F_BUNDLE_TS"

# Check file size
FILE_SIZE=$(stat -f%z "$OUTPUT_DIR/avatar-bundle.html" 2>/dev/null || stat -c%s "$OUTPUT_DIR/avatar-bundle.html" 2>/dev/null)
FILE_SIZE_KB=$((FILE_SIZE / 1024))

echo ""
echo "Build complete!"
echo "Output: $OUTPUT_DIR/avatar-bundle.html"
echo "Output: $R3F_BUNDLE_TS"
echo "Size: ${FILE_SIZE_KB}KB (uncompressed)"

# Check gzipped size
if command -v gzip &> /dev/null; then
  GZIP_SIZE=$(gzip -c "$OUTPUT_DIR/avatar-bundle.html" | wc -c)
  GZIP_SIZE_KB=$((GZIP_SIZE / 1024))
  echo "Size: ${GZIP_SIZE_KB}KB (gzipped)"

  if [ "$GZIP_SIZE_KB" -gt 500 ]; then
    echo ""
    echo "WARNING: Gzipped bundle size exceeds 500KB target!"
    echo "Consider optimizing dependencies or tree-shaking."
  else
    echo ""
    echo "Bundle size is within 500KB target."
  fi
fi
